### ISSUE TITLE
Input does not honor type attribute

### ISSUE THREAD

**Issue by mikeyGlitz** [daisyui/react-daisyui#101]
I've tried to create an `Input` with the following code:

```jsx
              <Input
                type="date"
                {...register('expirationDate', { required: true })}
              />
```

What I get when the DOM renders is:

```html
<input type="text" name="expirationDate" class="input focus:outline-offset-0 input-bordered" value="">
```

What I expected was:

```html
<input type="date" name="expirationDate" class="input focus:outline-offset-0 input-bordered" value="">
```

I believe this line needs to be changed:
https://github.com/daisyui/react-daisyui/blob/main/src/Input/Input.tsx#L48

```jsx
type={props.text}
```

Also, text shows up in the IDE auto-complete:
![image](https://user-images.githubusercontent.com/606924/164999736-edc8e44a-a1c8-470a-a03d-a5dca2c84620.png)

**Comment by benjitrosch** [comment]
Fixed with #102 . Thanks @mikeyGlitz!
