### ISSUE TITLE
Not able to generate new component

### ISSUE THREAD

**Issue by bannarisoftwares** [daisyui/react-daisyui#109]
Getting exception while running `npm run generate component Square`

**Output:**

```
npm run generate component Square 

> react-daisyui@2.0.1 generate
> plop "component" "Square"

/Users/****/Desktop/Temp/react-daisyui/node_modules/plop/bin/plop.js:3
import { Plop, run } from "../src/plop.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Expected:** create new component

**Comment by benjitrosch** [comment]
Hey @bannarisoftwares,

Thanks for reporting this. Could you post your `node` and `npm` versions? I'm going to try my best to reproduce your circumstances since it's currently working on my machine, and then try to find a fix.

**Comment by benjitrosch** [comment]
###### Removed this message because I misread something 😆

**Comment by bannarisoftwares** [comment]
Sorry for late reply... Node version = v12.13.0,
 npm = 8.6.0

**Comment by benjitrosch** [comment]
Thanks @bannarisoftwares. I will take a look!

**Comment by bannarisoftwares** [comment]
> @bannarisoftwares I just re-read this and I believe I understand the issue.
> 
> The `generate` command is intended for internal use to contribute to the react-daisyui codebase. I do not believe it will work outside that context. It seems you are trying to use it from your app, which has react-daisyui installed, to create a new component. However, that is not the intended use for `plop` in this project. To create components with react-daisyui, you should import the library from the top of your jsx/tsx file and access specific components that react-daisyui provides.

Hi @benjitrosch , I cloned this repo react-daisyui, and excecute this `npm run generate component NewComponent` cmd from root dir. of this folder... during that time... i am getting this error. am i wrong?

**Comment by benjitrosch** [comment]
My mistake, I misread your initial post. You are using it correctly!

I will investigate further based on your node version.

**Comment by bannarisoftwares** [comment]
> 

Sure @benjitrosch , Thank you for the support...

**Comment by benjitrosch** [comment]
@bannarisoftwares I just tested with Node 12.13.0 and got the same error as you. For plop to work please upgrade to at least Node 14 or above. I upgraded from 12.13.0 to 14.19.1 and was able to generate a component!

**Comment by bannarisoftwares** [comment]
> 

sure @benjitrosch .. I will try and let you know soon

**Comment by bannarisoftwares** [comment]
> @bannarisoftwares I just tested with Node 12.13.0 and got the same error as you. For plop to work please upgrade to at least Node 14 or above. I upgraded from 12.13.0 to 14.19.1 and was able to generate a component!

Working great after updated to v14... Thank you for the support @benjitrosch

**Comment by benjitrosch** [comment]
Very glad to hear it worked, always happy to help!

I used a tool called nvm (https://github.com/nvm-sh/nvm) which lets me install and use several different versions of Node at once. I find it very helpful for this sort of thing and always recommend it to people!

**Comment by bannarisoftwares** [comment]
> Very glad to hear it worked, always happy to help!
> 
> I used a tool called nvm (https://github.com/nvm-sh/nvm) which lets me install and use several different versions of Node at once. I find it very helpful for this sort of thing and always recommend it to people!

Got it.... Thank you..
