### ISSUE TITLE
NavBar.Center not in the center for wide screens

### ISSUE THREAD

**Issue by redxzeta** [daisyui/react-daisyui#127]
![image](https://user-images.githubusercontent.com/19883954/174652889-c9443eef-bf86-4c30-ac5d-66941da9a4d2.png)

**Comment by benjitrosch** [comment]
Hi @redxzeta,

From the look of it your `<Navbar.Center />` is centered but your content is left aligned. Have you tried adding `flex justify-center` to center your content within the `<Navbar.Center />`?
