### ISSUE TITLE
https://react.daisyui.com/ site is down

### ISSUE THREAD

**Issue by bannarisoftwares** [daisyui/react-daisyui#128]
https://react.daisyui.com/ is down,

Getting this error

Error 1016 Ray ID: 71eadc6d8f098602 • 2022-06-21 06:59:21 UTC
Origin DNS error
What happened?
You've requested a page on a website (react.daisyui.com) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (react.daisyui.com).

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS settings. If you are using a CNAME origin record, make sure it is valid and resolvable. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/234979888-Error-1016-Origin-DNS-error)

**Comment by benjitrosch** [comment]
Hi @bannarisoftwares,

Seems Cloudfare was down last night and took out half of the internet with it 😅! https://www.cloudflarestatus.com/incidents/xvs51y9qs9dj

Should be resolved now.
