### ISSUE TITLE
Create Tests for components

### ISSUE THREAD

**Issue by redxzeta** [daisyui/react-daisyui#137]
Unit / Integration testing  especially for all the stateful components

**Comment by redxzeta** [comment]
- [x] Alert
- [x] Artboard
- [x] Avatar
- [x] Badge
- [ ] Breadcrumbs
- [x] Button
- [ ] ButtonGroup
- [ ] Card
- [ ] Carousel
- [ ] Checkbox
- [ ] CodeMockup
- [ ] Collapse
- [ ] Countdown
- [ ] Divider
- [ ] Drawer
- [ ] Dropdown
- [x] Footer
- [ ] Form
- [ ] Hero
- [ ] Indicator
- [ ] Input
- [ ] InputGroup
- [ ] Kbd
- [ ] Link
- [ ] Mask
- [ ] Menu
- [x] Modal
- [ ] Navbar
- [ ] Pagination
- [ ] PhoneMockup
- [ ] Progress
- [ ] RadialProgress
- [x] Radio
- [x] Range
- [ ] Rating
- [ ] Select
- [ ] Stack
- [ ] Stats
- [ ] Steps
- [ ] Swap
- [ ] Table
- [x] Tabs
- [x] Textarea
- [ ] Theme
- [x] Toggle
- [ ] Tooltip
- [ ] WindowMockup

**Comment by imtheaman** [comment]
@benjitrosch May i get assigned this issue please?

**Comment by benjitrosch** [comment]
@urtheaman Sure, thank you!

**Comment by imtheaman** [comment]
@benjitrosch Thanks.

**Comment by redxzeta** [comment]
@urtheaman  how many of the tests did you cover? wondering if I could pick some of the leftover

**Comment by imtheaman** [comment]
Hey @redxzeta, could you please do from 32-47(RadialProgress - WindowMockup)?
I'm involved in multiple things right now, but i'll make the pr soon.

**Comment by benjitrosch** [comment]
@urtheaman Have you made any progress on any tests? I would prefer if you didn't "claim" any and instead simply make a PR per component as you finish them. That way we avoid blocking others who wish to contribute, and also keep the PR's a manageable size.

**Comment by imtheaman** [comment]
@benjitrosch okay. some of them are remaining. I'll submit 'em today or tomorrow.
Thanks.

**Comment by imtheaman** [comment]
@benjitrosch  I need some more time. hard to manage time b/w work, learnings and open source contributions.

**Comment by benjitrosch** [comment]
@urtheaman There's no pressure to do everything, and it's probably better that you don't! You can always just PR what you have and contribute more in the future depending on your schedule 😄

**Comment by imtheaman** [comment]
sure! once i finish the bugs on my current project(which will be done in
2-3 days). i'll be free for few days.

**Comment by erichartline** [comment]
Hi, is this checklist up to date? I might be able to help write some tests.

**Comment by benjitrosch** [comment]
@wildlifehexagon I believe so!

Ignore any comments claiming specific components, all PR's will be accepted on a first come first serve basis. So take whichever you like!

**Comment by wjdwl002** [comment]
May i get assigned some of them? (like around 2-3 would be good) 
I'm new to open source contribution so picking not really complicated ones for me would be appreciated !
Thanks

**Comment by benjitrosch** [comment]
Hi @wjdwl002,

Feel free to try any you would like. I will not be assigning components to anybody, but will review PR's as they come in. All of the components should be easy to test (for the most part they're light on state), so you can't go wrong in choosing!

**Comment by dev0T** [comment]
Hi @benjitrosch, is there a reason this got closed? It would be helpful to have an updated list of components that still need testing!
