### ISSUE TITLE
Is there documentation for react-daisyui?

### ISSUE THREAD

**Issue by nelsonlaidev** [daisyui/react-daisyui#145]
Thanks for this amazing library ❤️

UPDATED: I misunderstand that it is an official library

I don't know how to use react-daisyui + daisyui + Tailwindcss in Next.js

When I try to use them,  the CSS of daisyui is not loaded.

I found a tutorial before that I need to add `'node_modules/react-daisyui/dist/react-daisyui.cjs',` to tailwind config content.

After doing that it works, but there are some problems.
The CSS of class `btn-ghost` is not loaded.

My code:
```js
import { Button } from 'react-daisyui'

export default function Test() {
    return (
        <Button color="ghost">Test</Button>
    )
}
```

![Snipaste_2022-06-27_19-07-46](https://user-images.githubusercontent.com/75498339/175927863-a5fd6015-e191-4209-8ff5-58d0155ed551.png)

**Comment by benjitrosch** [comment]
Hi @TszHong0411,

No worries, this is the official library! 😄 

I'm not sure which tutorial you followed (could you link it?) but the correct path would be `"node_modules/daisyui/dist/**/*.js"`. Give that a try and let me know if that fixes it for you!

**Comment by nelsonlaidev** [comment]
> Hi @TszHong0411,
> 
> No worries, this is the official library! 😄
> 
> I'm not sure which tutorial you followed (could you link it?) but the correct path would be `"node_modules/daisyui/dist/**/*.js"`. Give that a try and let me know if that fixes it for you!

Thanks a lot. It works.
Oh, It is an issue of this repo. #100 
My fault 😂
