### ISSUE TITLE
<Select.Option/>'s `onChange(Event)` can't get the `value` prop/attribute

### ISSUE THREAD

**Issue by neotan** [daisyui/react-daisyui#147]
**Reproduction:**
https://codesandbox.io/s/react-daisyui-example-forked-x46041?file=/src/App.tsx

**Expected behavior (in plain HTML):**
Should get the `value` attribute 
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Actual result:**
Getting the `inner text` of `<Select.Option>INNER TEXT</Select.Option>`

**Related code:**
The root cause should be the missing `value` prop here
https://github.com/daisyui/react-daisyui/blob/7b97f481f087c97349f6c934e9e51c545ee560b6/src/Select/SelectOption.tsx#L18

**Comment by benjitrosch** [comment]
Hi @neotan,

Taking a look at the codesandbox, the version of `react-daisyui` is `1.7.4`, which had some issues with types that have since been resolved. Upgrade to a more recent version, like `2.0.4`, and you shouldn't have a problem!

**Comment by benjitrosch** [comment]
Hi @neotan,

Thanks for finding this! I've added the missing value prop to the `SelectOption` it with this PR:

https://github.com/daisyui/react-daisyui/pull/148

**Comment by benjitrosch** [comment]
@neotan the fix for this has been released with 2.0.5, closing the ticket now.
