### ISSUE TITLE
feature request: tag prop on Theme component

### ISSUE THREAD

**Issue by justinmetros** [daisyui/react-daisyui#161]
Feature Request:
- allow for `tag` prop ( or similar ) on `Theme` component so it can be rendered as an element [other than `div`](https://github.com/daisyui/react-daisyui/blob/1efbc390c7824180a6eb1b2b6ac0cd22f70acfbe/src/Theme/Theme.tsx#L49)

Use Case:
```js
<Theme tag="body" dataTheme="dark">
  <main>{children}</main>
</Theme>
```
Output:
```js
<body data-theme="dark">
  <main>
    <div>Hello World</div>
  </main>
</body>
```

Will try to open a PR if space allows and this interests the team, but floating this idea up in the meantime. 

Thanks for all the work on this, so awesome!

**Comment by benjitrosch** [comment]
Hey @justinmetros,

Great idea! If you want to open a PR that would be great, otherwise I can take a look at this during the week and try to open a PR.
