### ISSUE TITLE
Bug: React Drawer input checkbox  throws warning

### ISSUE THREAD

**Issue by awolkers** [daisyui/react-daisyui#167]
When using the (react) Drawer the following warning is thrown.
 _You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`._

**Comment by benjitrosch** [comment]
Hi @awolkers,

Thanks for finding this! The warning message should go away after #169 is merged. Until then, feel free to ignore it!
