### ISSUE TITLE
Collapse checkbox cannot close on mobile browser (os: ios 15.5)

### ISSUE THREAD

**Issue by oentoro** [daisyui/react-daisyui#168]
Hi,i have an issue when using collapse (with checkbox) on mobile browser (chrome, safari)
[Try this on mobile browser](https://react.daisyui.com/?path=/story/data-display-collapse--checkbox)

**Comment by benjitrosch** [comment]
Hi @oentoro,

Thanks for finding this. I'm able to reproduce on my mobile as well... very strange! I'll look for a fix this weekend and open a PR.

**Comment by arvigeus** [comment]
As per [this PR](https://github.com/saadeghi/daisyui/pull/784), the problem is `tabIndex` on div element. When `checkbox` is true, `tabIndex` should be placed on the `<input type="checkbox">` element,
