### ISSUE TITLE
Does react-daisyui support Modularize Imports 

### ISSUE THREAD

**Issue by tianyingchun** [daisyui/react-daisyui#170]
for now many front end libaray support `Modularize Imports ` it will can reduce app bundle size, such as next.js, and so on. could you plan to support this?

**Comment by benjitrosch** [comment]
Hi @tianyingchun,

I'm afraid I do not understand what you are asking. Are you perhaps asking if using named imports will increase bundle size, or if tree shaking will work with your bundler/framework (sounds like you're using Next.js)?

**Comment by tianyingchun** [comment]
@benjitrosch  sure you are right: i am use next.js, in fact other framework also support this, tree-shaking.

`import {Theme} from 'react-daisyui'` it will only import `react-daisyui/theme` it's fine,
