### ISSUE TITLE
The Dropdown didn't handle its custom className from its props properly

### ISSUE THREAD

**Issue by neotan** [daisyui/react-daisyui#209]
## Issue:
If I try passing a custom classname, the Dropdown didn't pass/merge it with other classnames properly.

### Input
```tsx
<Dropdown className="custom-classname" >
```
### Expected output
```html
<div role="listbox" class="dropdown custom-classname">
```
### Actual output
```html
<div role="listbox" class="dropdown">
```

**Comment by benjitrosch** [comment]
@neotan Thanks for finding and fixing this!

**Comment by neotan** [comment]
> @neotan Thanks for finding and fixing this!

Glad to contribute to this amazing UI lib. Cheer!🍻
