### ISSUE TITLE
Checkbox - controlled/uncontrolled components warning when specify `checked` property

### ISSUE THREAD

**Issue by bboyz269** [daisyui/react-daisyui#213]
**Issue**
Due to `defaultChecked` is always set internally, if `checked` is also set, warning is thrown
> Warning: Checkbox contains an input of type checkbox with both checked and defaultChecked props. Input elements must be either controlled or uncontrolled (specify either the checked prop, or the defaultChecked prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://reactjs.org/link/controlled-components
    at input
    at eval (webpack-internal:///../../node_modules/react-daisyui/dist/react-daisyui.modern.js:4689:24)

**Point of interest**: https://github.com/daisyui/react-daisyui/blob/8887f5f93567b683a1d74024a4da65a80fec5798/src/Checkbox/Checkbox.tsx#L26-L37

**Suggestion**: Don't set default value for `defaultChecked` or better yet, remove them both (leave it to `{...props}`)

**Comment by benjitrosch** [comment]
Hi @bboyz269, great catch! Thank you for finding this!

I'll label this as a `Good First Issue` if anybody looking for an easy first contribution wants to tackle and implement the suggested fix. I'm in favor of removing them entirely and leaving it up to props as you said.

**Comment by Klaas058** [comment]
I'd be happy to implement the fix, as you said, both properties can be removed.
Both the `checked` and `defaultChecked` are part of the HtmlInputElement props so removing them won't effect property suggestions either.

Are you ok with me implementing the fix @benjitrosch? since it's not my first issue.

**Comment by benjitrosch** [comment]
@Klaas058 yeah, that's no problem-- PR's are on a first-come-first-serve basis, so feel free!
