### ISSUE TITLE
Rating component does not work as expected

### ISSUE THREAD

**Issue by cyr-l** [daisyui/react-daisyui#215]
Hi 👋,

I'm experiencing erratic behavior with the `Rating` component.

The issue occurs locally and on the [documentation site](https://react.daisyui.com/?path=/story/data-input-rating--default).

https://user-images.githubusercontent.com/215009/190849229-80beff6f-1a7a-41cd-b69f-6e544a9a0a83.mov

**Comment by cyr-l** [comment]
Oh, it looks like it is coming from the `checked` attribute (second item in the doc).

If I remove it, the component is working correctly.

Maybe this is supposed to be `defaultChecked` instead?

**Comment by willmatos** [comment]
@benjitrosch 

First off thanks for all the work on this project! Truly awesome and I'm enjoying using it.

I am also running into issues with the Rating component in regards to the checked functionality. My build doesn't seem to be picking up a specific style `.rating input:checked ~ input, .rating input[aria-checked=true] ~ input { --tw-bg-opacity: 0.2; }` for the inputs that follow the checked input. I pulled down the repo to fix the issue and tracked it down to the styles from the `main.97780222.iframe.bundle.js` not being picked up. How and from which files do the styles and this file get created?

Working in the React-DaisyUI Storybook:
![Screen Shot 2022-09-22 at 2 55 18 PM](https://user-images.githubusercontent.com/847623/191851443-99c6335f-1f9f-4895-bb0f-dbaba35b3a5b.png)

Not working in my build:
![Screen Shot 2022-09-22 at 2 54 37 PM](https://user-images.githubusercontent.com/847623/191851569-65cacc59-e466-43d3-b5f2-6a27b2656552.png)
