### ISSUE TITLE
Popups should use portals 

### ISSUE THREAD

**Issue by mattiaz9** [daisyui/react-daisyui#225]
Popups such as modals and dropdowns should use portals for the content to avoid problems with overflow: hidden or z-indexes.

**Comment by benjitrosch** [comment]
Hi @mattiaz9,

Indeed they should, however the portal implementation should be left up to users. While React/CRA could just use `ReactDOM.createPortal()`, Next.js might render server side where the `document` and `window` object do not exist and would require a `typeof window !== 'undefined'` check.
