### ISSUE TITLE
Tooltip positional classes not working

### ISSUE THREAD

**Issue by Pr0dt0s** [daisyui/react-daisyui#234]
The positional classes are not being picked up from source files. Seems to be related to a change some time ago from safelisting every class to using content as per instrunction in the README file:

https://github.com/daisyui/react-daisyui/blob/50b25e687ccae19110a425ca6c94b79f6519d02b/README.md?plain=1#L35-L42

Line number 39 in Tooltip.tsx seems to be the problem; It is interpolating a class making tailwind unable to detect correctly.
https://github.com/daisyui/react-daisyui/blob/50b25e687ccae19110a425ca6c94b79f6519d02b/src/Tooltip/Tooltip.tsx#L33-L41

Here is a print and a stackblitz link showing the problem:

![image](https://user-images.githubusercontent.com/24417072/195418515-b771c118-48e1-41a0-a3a0-e5141f5bc1b4.png)
[Example on stackblitz](https://stackblitz.com/edit/vite-react-daisyui-3fx123?file=src%2FApp.tsx)

I would like to try and submit a pull request with a fix. But wanted to discuss a bit about the best path to take.

This problem may very well be affecting other components too. I just found a mention of it in issue #116

**Comment by Klaas058** [comment]
Hi @Pr0dt0s thanks for opening the issue.

This doesn't seem to be an interpolation issue, the classes get put on correctly but the tooltip position classes do not seem to exist. 
I've tested this locally too, editing the Tooltip component, removing the interpolation, and forcing the `tooltip-left`  class directly on the component (and the bottom, top, right classes too for that matter).
The classes do not seem to exist in the css inside the DOM either.

I'm curious what is causing the problem, hope someone else has better luck.

**Comment by Pr0dt0s** [comment]
Hi @Klaas058, I just tested this fix and it worked, maybe I did something diferent, can you check out PR #235.

If this is the path forward, what do you think of refactoring all the string interpolations?

It would defenitely follow [tailwind´s guidelines](https://tailwindcss.com/docs/content-configuration#dynamic-class-names) regarding classnames in file contents.

**Comment by Klaas058** [comment]
Hi @Pr0dt0s, I've responded in PR #235 with a [comment](https://github.com/daisyui/react-daisyui/pull/235#issuecomment-1282009893).

You're right that it would be following the tailwind guideline.
But if upgrading the `tailwind-merge` dev dependency to `^1.6.2` works then I vote for that.
