### ISSUE TITLE
I can´t set Dropdown.Item as active

### ISSUE THREAD

**Issue by cstaleror** [daisyui/react-daisyui#243]
I´m trying to create a dropdown and set one item as active but I can't, I have to use Menu.Item with a div as child with 'active' class. I'd like to set 'active' as prop (No className)... Thank you

**Comment by Klaas058** [comment]
Hi @cristianTalero,

I'm a little confused by your question.
The DaisyUI Dropdown component doesn't have an 'active' class or alike.
Can it be you are looking for something like the [Select](https://react.daisyui.com/?path=/story/data-input-select--default) component?

If not, can elaborate a bit on the issue?

**Comment by cstaleror** [comment]
@Klaas058 Thanks for your answer

I can't set dropdown menu item as active, 'active' class doesn't work

**Comment by Klaas058** [comment]
You're welcome @cristianTalero,

As far as I am aware the [Dropdown](https://daisyui.com/components/dropdown/) from DaisyUI is not built for that use case.
The dropdown component just drops stuff down ^^.
We do not typically add or change any behavior, just merely build the css+html into React components.
If you want to have an active class, you are free to add that functionality to your implementation :)

**Comment by benjitrosch** [comment]
Hi @cristianTalero,

Perhaps you're looking for the `open` prop to force the `<Dropdown>` to be open without user interaction? If not, could you elaborate on what you're trying to achieve with it?
