### ISSUE TITLE
Typescript types haven't been generated in the last release

### ISSUE THREAD

**Issue by mattiaz9** [daisyui/react-daisyui#246]
I get the classic error `Could not find a declaration file for module 'react-daisyui'`

Version `2.4.4` works fine.

**Comment by cefn** [comment]
I have this same issue. Projects that worked in 2.4.4 are now showing no typing information for react-daisyui, breaking builds. 
![image](https://user-images.githubusercontent.com/159819/199273183-48a514ce-dd82-46d3-b3d6-dc6e536a232d.png)

**Comment by benjitrosch** [comment]
Thanks for finding this @mattiaz9 and @cefn. I'll take a look at all the commits since 2.4.4 and try to identify the issue!

**Comment by xaamin** [comment]
Hi,

I created a PR [247](https://github.com/daisyui/react-daisyui/pull/247) to fix this issue introduced by the setup of jest-dom library used by testing in the most recent release. 

Adding a new file outside of src path was accidentally causing the compiler to copy out the whole src directory in the dist folder.

@benjitrosch do you mind adding a code-owner approval if this looks good?

**Comment by benjitrosch** [comment]
Fixed by @xaamin's PR. Thanks!
