### ISSUE TITLE
How to apply different colors for Range component?

### ISSUE THREAD

**Issue by pmrzygweb** [daisyui/react-daisyui#256]
color prop only accepts primary, secondary, accent?

**Comment by benjitrosch** [comment]
Hi @pmrzygweb, seems these additional colors for the `Range` component became available in daisyui version 2.35.0. I'll update our package version accordingly to bring in these new changes!

**Comment by pmrzygweb** [comment]
@benjitrosch I have another issue with tabs, can't find a variant "boxed", only "lifted" and "bordered" are available

**Comment by benjitrosch** [comment]
@pmrzygweb Fixed the missing color props with this #259. Will take a look at tabs next. Sorry for the delay-- been busy lately.

**Comment by benjitrosch** [comment]
@pmrzygweb `boxed` is a separate prop from `variant`, so you can toggle it regardless of the variant (or lack thereof).
