### ISSUE TITLE
Add new Chat Bubble component

### ISSUE THREAD

**Issue by benjitrosch** [daisyui/react-daisyui#262]
Implement the `<Chat>` component added in daisyui 2.42: xhttps://daisyui.com/components/chat/

**Comment by tino-brst** [comment]
Will take a look at this one* 👍

*Results not guaranteed

**Comment by yurisldk** [comment]
@benjitrosch @tino-brst PR #270 is created and ready for review. 

![image](https://user-images.githubusercontent.com/118747540/206652656-21071173-9a18-41a6-a4c1-91361fa1bc33.png)
Thank you.
