### ISSUE TITLE
Add new File Input Component

### ISSUE THREAD

**Issue by benjitrosch** [daisyui/react-daisyui#263]
Implement the `<FileUpload>` component added in daisyui 2.40: https://daisyui.com/components/file-input/

**Comment by bhavesh-10x** [comment]
Hey, I am interested to work on it. Can you assign this to me?

**Comment by BParvatkar** [comment]
Hey, I am interested to work on it. Can you assign this to me?

**Comment by benjitrosch** [comment]
@BParvatkar we do not assign. Instead, fork the repo and then open a PR.

**Comment by BParvatkar** [comment]
Have opened a pr, @benjitrosch  #273.
