### ISSUE TITLE
[Help] Any simple way of closing dropdow on click?

### ISSUE THREAD

**Issue by AlexandreRoba** [daisyui/react-daisyui#275]
Hi all,

This is my code. i've been working 2 hours on trying to find a way to close the dropdown on click... How can I achieve this?

There is an open attribute...How do I get the reference to it on the handler? I tried using useRef() whitout any success. i cannot find the proper type... :(

```
const handleOnClick = (l: string) => {
    router.push({ pathname, query }, asPath, { locale: l });
  };

  return (
    <Dropdown>
      <Dropdown.Toggle color="ghost">{locale.toUpperCase()} </Dropdown.Toggle>
      <Dropdown.Menu>
        {locales.map((l) =>
          <Dropdown.Item key={l} onClick={() => handleOnClick(l)}>{l?.toUpperCase()}</Dropdown.Item>
        )}
      </Dropdown.Menu>
    </Dropdown>
```

**Comment by benjitrosch** [comment]
Hi @AlexandreRoba, see this thread for a few different ways to do this:

https://github.com/saadeghi/daisyui/issues/157
