### ISSUE TITLE
Carousel control button

### ISSUE THREAD

**Issue by Xoaib007** [daisyui/react-daisyui#282]
![Screenshot 2022-12-25 230148](https://user-images.githubusercontent.com/55616502/209483005-aae4e7bc-b4f9-477b-81b3-65fedacfff38.png)

Carousel control buttons uses anchor tag which cause re-rendering the page. Which is inappropriate in a single page project with react.

**Comment by benjitrosch** [comment]
Hi @Xoaib007,

I think there may be some misunderstanding. The code snippet you've posted belongs to https://daisyui.com/components/carousel/, which is different from the React based version found on https://react.daisyui.com/?path=/story/data-display-carousel--sequential.

The React version appropriately uses a `<button>` by default, and allows the user to pass in any custom button they would like to use. The anchor tag makes sense for the non-React daisyui example.

**Comment by Xoaib007** [comment]
> Hi @Xoaib007,
> 
> I think there may be some misunderstanding. The code snippet you've posted belongs to https://daisyui.com/components/carousel/, which is different from the React based version found on https://react.daisyui.com/?path=/story/data-display-carousel--sequential.
> 
> The React version appropriately uses a `<button>` by default, and allows the user to pass in any custom button they would like to use. The anchor tag makes sense for the non-React daisyui example.

Thanks man, I didnt know daisyui have a dedicated react based version. I've been using wrong thing for almost 8 months :)
