### ISSUE TITLE
Dropdown.Toggle does not have all button properties

### ISSUE THREAD

**Issue by santiagoraigoso** [daisyui/react-daisyui#291]
### What happened?

I was trying to get a round dropdown toggle button, but trying to use <Dropdown.Toggle shape="circle"> didn't change the shape, since in the library code this property is not added

### Library code:
![image](https://user-images.githubusercontent.com/95507613/213069025-e90bfa7a-8dd6-47de-9adf-815d287b0105.png)

**Comment by benjitrosch** [comment]
Hi @Withervoid77,

If you take a look, you can change the `button` prop to false in order to render your own custom `<Button>` with a circle shape. That being said, maybe in the future we can expose something like `buttonProps`.

**Comment by santiagoraigoso** [comment]
Ok, thank you very much for your help.
