### ISSUE TITLE
Avatar borderColor not working

### ISSUE THREAD

**Issue by kaeon** [daisyui/react-daisyui#295]
When I use an avatar borderColor doesn't get applied:

`<Avatar src="/img/user2.png" size="xs" shape="square" online border borderColor="success" className="mt-1 ml-5 mr-1" />`

For some reason the issue comes from class ring when I check with devTools:

`.ring {
    --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
    --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(3px + var(--tw-ring-offset-width)) var(--tw-ring-color);
    box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000);
}`

The real color I get comes from **--tw-ring-color**. Strangly it does seem to work on the demo https://react.daisyui.com/?path=/story/data-display-avatar--ring&args=borderColor:warning;shape:square;online:true;size:sm

**Comment by benjitrosch** [comment]
Should be fixed as of release 3.1.0
