### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by xedef** [daisyui/react-daisyui#298]
Is there any place that documents all of the components API?

**Comment by benjitrosch** [comment]
Hi @xedef,

Depends what you're looking for. At the moment, the best documentation would be the Storybook found here: https://react.daisyui.com/

From each component's Storybook page you can see all of their props and how they affect the component's style/functionality— in addition to several examples that mirror the examples on https://daisyui.com/.

As far as written documentation goes, nothing exists at the moment, and I'm not of the opinion that it would be more helpful than the Storybook.
