### ISSUE TITLE
Broken route transition on Button with Next.js Link component

### ISSUE THREAD

**Issue by batgos** [daisyui/react-daisyui#307]
When I use a Button as a child of a Next/Link component with Href, the Next.js client-side route transition is not working and a reload is applied to my app when accessing the page

Example :
```
import Link from 'next/link';
import { Button } from 'react-daisyui';

<Link href="/admin/staff-invitations" legacyBehavior passHref>
     <Button color="primary">{t('invitation-list')}</Button>
</Link>
```

**Comment by dev0T** [comment]
This seems related to #108
