### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by CMiksche** [daisyui/react-daisyui#322]
The website currently displays `Failed to fetch dynamically imported module: https://react.daisyui.com/assets/preview-bb5acd95.js`:

```
TypeError: Failed to fetch dynamically imported module: https://react.daisyui.com/assets/preview-bb5acd95.js
```

**Comment by benjitrosch** [comment]
Hi @CMiksche,

Thanks for catching that. This morning I merged a PR to upgrade our Storybook to v7 (which required a migration for some hefty breaking changes) as well as a few other deps that were upgraded. Something must have broken. I'll take a look!

**Comment by benjitrosch** [comment]
The build works locally as well as on the Netlify preview, but fails on GitHub Pages. Seems other people are experiencing the exact same thing: https://github.com/storybookjs/storybook/issues/20564

Implemented the fix as described above (by adding this file https://github.com/daisyui/react-daisyui/blob/main/docs/.nojekyll to the root of our pages) and the build appears to be fixed.

**Edit:** seems to still be broken. 
**Edit2:** after testing with a few other computers, I've deleted the cache and hard-reloaded from my main laptop to find it working again 👍
