### ISSUE TITLE
Storybook is broken

### ISSUE THREAD

**Issue by dev0T** [daisyui/react-daisyui#326]
Hello!

I wanted to check the previews on Storybook but apparently, the app isn't working. I mainly use Firefox but attempted to open it on Chrome and got the same result.

Google Chrome:

![image](https://user-images.githubusercontent.com/28127196/229949693-0d20024e-e5ed-4b30-9c9a-dec86f549cec.png)

Firefox:
![image](https://user-images.githubusercontent.com/28127196/229949725-0d1ed4c5-3258-4e5f-928e-92e45d5687ea.png)

**Comment by benjitrosch** [comment]
Hi @dev0T ,

Looks like this was related to upgrading to Storybook v7 this morning (see https://github.com/daisyui/react-daisyui/issues/322).

I managed to fix it for myself by hard refreshing, let me know if that works for you! Not sure yet if it's actually broken or just some weird issue when the old version is cached.

**Comment by dev0T** [comment]
Unfortunately, I haven't used the Storybook until this afternoon so that wouldn't be the case!

Here are the errors I am getting in the browser console:

![image](https://user-images.githubusercontent.com/28127196/229954170-6fcc4009-d82a-4cac-b495-e7f3707fe206.png)

**Comment by benjitrosch** [comment]
Ahh, looks like the fix from earlier today that added the `.nojekyll` file to the `/docs` folder was overwritten when I re-released. I've added logic to the `npm run docs` script to create the file every time it runs so that won't happen anymore.

Unfortunately @dev0T that means you will still need to do the hard refresh, still haven't found a way around that. Thanks again for finding this, and sorry again for the outage making it so hard to see the components 😅 

<img width="373" alt="Screen Shot 2023-04-04 at 9 13 15 PM" src="https://user-images.githubusercontent.com/64439681/229956271-94963d00-196f-4572-8b0f-17b6bfe14120.png">

**Comment by dev0T** [comment]
Thank you @benjitrosch!

I have it working on Chrome. Firefox isn't working no matter what I do though 😅

![image](https://user-images.githubusercontent.com/28127196/229966859-a4cef5ed-b8b8-4760-9cbe-3ed96cef23f7.png)

Probably something on my end, I will keep trying

**Comment by benjitrosch** [comment]
Not just you, I downloaded Firefox and it's happening for me as well. I'll continue to try and maybe open an issue with Storybook if I can't get to the bottom of it!

**Comment by dev0T** [comment]
I have forked the repo and while running the storybook locally with npm start it is working on Firefox without issues. 

Also realized that the deployment preview from my latest PR is working.

**Comment by benjitrosch** [comment]
Yeah unfortunately the problem only happens on GItHub Pages, but not locally or on Netlify. Seems other users report the exact same thing. Makes the problem very hard to fix and very easy to miss until it's too late 😢

**Comment by dev0T** [comment]
> Yeah unfortunately the problem only happens on GItHub Pages, but not locally or on Netlify. Seems other users report the exact same thing. Makes the problem very hard to fix and very easy to miss until it's too late 😢

Looks like it is broken again on Chrome today. Hard reload isn't working unfortunately

Error is different though:

![image](https://user-images.githubusercontent.com/28127196/230463590-70c675d3-b5ff-4a72-b2b7-4f52168b16d6.png)

**Comment by benjitrosch** [comment]
Yikes. I'm going to prioritize fixing this over the weekend, not a great look for the library!

**Comment by dev0T** [comment]
I did a bit of research but couldn't find anything related that could help. :disappointed:

I don't know what is being used to build Storybook for github pages, but if I could guess I'd say the issue is there

**Comment by benjitrosch** [comment]
Finally working for me on Safari after changing how pages are built but still no luck on Firefox.

**Comment by rolowilde** [comment]
Still borked on Firefox, but works as expected on Chrome.

**Comment by samuelkarani** [comment]
Still broken

**Comment by samuelkarani** [comment]
Broken again
<img width="1700" alt="Screenshot 2023-04-12 at 22 52 45" src="https://user-images.githubusercontent.com/21354170/231582417-9cd537af-572d-40d1-999e-d3978a15cfe6.png">

**Comment by benjitrosch** [comment]
Looks like it's re-broken on Safari 😕

**Comment by benjitrosch** [comment]
Opened an issue in the storybook repo, hopefully they can offer more insight: https://github.com/storybookjs/storybook/issues/22094

**Comment by benjitrosch** [comment]
As a temporary fix to bring the Storybook deployment back online, I've reverted the `/docs` folder to release 3.0.3.

**Comment by dev0T** [comment]
@benjitrosch I was going to suggest that since my research was directing me to Storybooks issues all the time! Hopefully someone can help with a solution

**Comment by dev0T** [comment]
@benjitrosch I don't know what happened but its working

![image](https://user-images.githubusercontent.com/28127196/233168687-8c39530b-06fe-4ca5-8f20-4b3387d72c3e.png)

**Comment by benjitrosch** [comment]
@dev0T That's the old deployment unfortunately, which means we can't release a new version without breaking it again 😅

**Comment by dev0T** [comment]
I will be closing this since it appears the issue has been fixed.
