### ISSUE TITLE
Circular Dependency in ChatBubbleAvatar

### ISSUE THREAD

**Issue by dev0T** [daisyui/react-daisyui#329]
While getting familiar with the library codebase I realized a message regarding a Circular Dependency when running `npm run dist`:

```bash
Circular dependency: src/index.ts -> src/ChatBubble/index.ts -> src/ChatBubble/ChatBubble.tsx -> src/ChatBubble/ChatBubbleAvatar.tsx -> src/index.ts
```

This is caused by the ChatBubbleAvatar importing Avatar from src/index.ts instead of src/Avatar.

The current import looks like this:
```js
import { Avatar, AvatarProps } from '..'
```
When they should be:
```js
import Avatar, { AvatarProps } from '../Avatar'
```

I am making a PR to fix it right now.

**Comment by benjitrosch** [comment]
Thanks for finding this, approved the PR!
