### ISSUE TITLE
Stat.Item

### ISSUE THREAD

**Issue by recidive** [daisyui/react-daisyui#338]
In story book the `Stats` component has `Stat.Item`. It looks like`Stat` is not exported? I'll investigate further.

**Comment by dev0T** [comment]
Yes, if you need to use `Item` you need to use it was `Stats.Stat.Item`. The storybook is giving the incorrect example since it isn't using the library on how it is exported, as it has access to everything.

I will create a PR that fixes the example in a bit

**Comment by dev0T** [comment]
@benjitrosch I think this can be closed since my merged PR has already been merged!

**Comment by benjitrosch** [comment]
@dev0T good catch, thanks!
