### ISSUE TITLE
Component examples that use lorem.space are missing images

### ISSUE THREAD

**Issue by dev0T** [daisyui/react-daisyui#340]
[lorem.space](https://lorem.space/) isn't maintained anymore, so many components in the storybook aren't showing images properly:

- [ ] Carousel
- [ ] Hero
- [ ] Mask

There might be a few more but I couldn't find them. I did a research and found [Lorem Picsum](https://picsum.photos/). We could change the examples to use these or change the examples to use static images (what DaisyUI currently does) which will avoid this issue in the future.

If we use static images we could use the same images DaisyUI uses for their examples.

**Comment by benjitrosch** [comment]
Good catch, thanks @dev0T ! We should use the same static images the main DaisyUI site uses.

**Comment by dev0T** [comment]
Fixed by #355.
