### ISSUE TITLE
Implment Daisy UI tabs like flowsbite tabs

### ISSUE THREAD

**Issue by cooljameswei** [daisyui/react-daisyui#350]
Is there any implement `Daisy UI tabs `like `flowbite `tabs looks clean and easy to reusable.
https://flowbite-react.com/tabs

https://react.daisyui.com/?path=/story/navigation-tabs--lifted&args=value:3

And through this link there're some issues that DaisyUI react doesn't support Tab.
So instead of following doc I used `Tabs.Tab`.
Is is that I missed something important in DaisyUI.

```
                <Tabs.Tab value={0} className="btn btn-ghost mt-10 mr-10">
                    ongoing
                </Tabs.Tab>
                <Tabs.Tab value={1} className="btn btn-ghost">
                    completed
                </Tabs.Tab>
```

**Comment by dev0T** [comment]
> And through this link there're some issues that DaisyUI react doesn't support Tab. So instead of following doc I used `Tabs.Tab`. Is is that I missed something important in DaisyUI.
> 
> ```
>                 <Tabs.Tab value={0} className="btn btn-ghost mt-10 mr-10">
>                     ongoing
>                 </Tabs.Tab>
>                 <Tabs.Tab value={1} className="btn btn-ghost">
>                     completed
>                 </Tabs.Tab>
> ```

That's the correct usage, unless you deconstruct Tabs on top of your component file. The documentation is a bit confusing regarding that so it would be nice to have it updated

**Comment by cooljameswei** [comment]
Thanks for clarification!
