### ISSUE TITLE
Modal background is clickable

### ISSUE THREAD

**Issue by lorenzobalzani** [daisyui/react-daisyui#356]
I think it's a bug. As we can see at this [link](https://daisyui.com/components/modal/), when the modal opens up, the background becomes inactive and thus not clickable. Are there any chances to achieve this behavior?

**Comment by benjitrosch** [comment]
Hi @lorenzobalzani, I'm not sure I understand the question. We already have this functionality, you can see it in action here: https://react.daisyui.com/?path=/story/actions-modal--default

**Comment by lorenzobalzani** [comment]
> Hi @lorenzobalzani, I'm not sure I understand the question. We already have this functionality, you can see it in action here: https://react.daisyui.com/?path=/story/actions-modal--default

If I open this modal, I‘m still able to scroll and interact with the background.

**Comment by lorenzobalzani** [comment]
> > Hi @lorenzobalzani, I'm not sure I understand the question. We already have this functionality, you can see it in action here: https://react.daisyui.com/?path=/story/actions-modal--default
> 
> If I open this modal, I‘m still able to scroll and interact with the background. 

In Daisy UI, when a modal shows up, the background becomes inactive and thus, not scrollable. I think this would be the right behavior also for this library since it should be a wrapper.
