### ISSUE TITLE
DaisyUI 3 peer dependency & compatibility 

### ISSUE THREAD

**Issue by snnyvrz** [daisyui/react-daisyui#360]
Hello there, 

I've tried to install react-daisyUI 3.1, but the package manager warns: "Unmet peer dependency" and says the correct version of daisyUI should be ^2.52.0 while the installed version is 3.0.22.

I wanted to know if there's a plan to update the dependency.

Thanks in advance

**Comment by benjitrosch** [comment]
Hey @snnyvrz thanks for bringing this up, I've got to update the peer dependencies of the library to match the latest version of daisyUI. For now you can downgrade your daisyui version to 2.52.0.

**Comment by matthewmichel** [comment]
Would love to have this pushed soon. This makes DaisyUI 3 pretty much unusable in production which really is a shame.

**Comment by benjitrosch** [comment]
@matthewmichel I'm not sure I would agree, it's more than useable as long as you don't need the most up to date version of daisyui. I've been pretty swamped with work lately and haven't had time to go through the changelog and match every update, but I'll try to get to it soon. PR's are always welcome of course 😄

**Comment by akme** [comment]
Also would love to see new release :) can't wait to play with the new and shiny daisyUI 😄

**Comment by akme** [comment]
New release works great! Thanks

**Comment by benjitrosch** [comment]
@akme glad it didn't take too long haha, you can thank @yoshi6jp for handling most of the updates for daisy v3!
