### ISSUE TITLE
Button loading prop does not work when startIcon is set

### ISSUE THREAD

**Issue by jisensee** [daisyui/react-daisyui#389]
Basically title. When a button has a `startIcon` set and `loading = true`, neither the loading indicator nor the icon are displayed.
The bug is directly in the button implementation as far as I can tell:
https://github.com/daisyui/react-daisyui/blob/fba1e1b68874b5c80c52c611a3a8bdc2ab6e5464/src/Button/Button.tsx#L165
The loading indicator will never be shown when a `startIcon` is set. However, previously (before the last major update) it would replace the `startIcon`. So this condition just has to lose the `!startIcon` part I think.

**Comment by benjitrosch** [comment]
@jisensee thanks for finding this. You're right, removing the `!startIcon` condition would fix this. Do you want to submit the PR?

**Comment by benjitrosch** [comment]
Fixed with ecb4add
