### ISSUE TITLE
[4.0.1]: `Join` component not exported by the module

### ISSUE THREAD

**Issue by exoRift** [daisyui/react-daisyui#397]
Although `ButtonGroup`s and `InputGroup`s are deprecated in favor of `Join`s, the `Join` component isn't actually exported by the module

**Comment by benjitrosch** [comment]
@exoRift good catch, thanks for finding this. Fixed with https://github.com/daisyui/react-daisyui/commit/095425b4111b73999c2812ba86fbe52a42e68110.
