### ISSUE TITLE
Add `cursor: default` to the Modal backdrop button

### ISSUE THREAD

**Issue by exoRift** [daisyui/react-daisyui#403]
`<button>` tags by default have `cursor: pointer` in Tailwind. However, expected behavior and user experience for a Modal backdrop is to be the default cursor, not the pointer.

**Comment by benjitrosch** [comment]
@exoRift the cursor style only gets applied when you set the `backdrop` prop to `true`. Otherwise the backdrop is not interactive and would be a misleading experience.

**Comment by exoRift** [comment]
My suggestion is to keep the backdrop interactive while having a regular cursor. I don't believe I've ever seen a modal with a clickable backdrop that had `cursor: pointer`

**Comment by benjitrosch** [comment]
You're free to remove the styling yourself. However, the `cursor: pointer` on interactive Modal backdrops is a part of the daisyui design system, and I can't see any benefit to removing the styles, only a loss for accessibility and user experience.
