### ISSUE TITLE
ModalLegacyProps type is not exported

### ISSUE THREAD

**Issue by tmartensen-hobsons** [daisyui/react-daisyui#404]
I've noticed in `src/index.ts` that `ModalProps` are exported: 
```export type ModalProps = TModalProps```

but `LegacyModalProps` are not. IDE tries to infer them from `'react-daisyui/dist/Modal`, but it throws an eslint `import/no-unresolved` error. Should `ModalLegacyProps` be exported like the new `ModalProps`?

**Comment by tmartensen-hobsons** [comment]
I've opened a PR (#405) to account for this, if that's OK.

**Comment by benjitrosch** [comment]
@tmartensen-hobsons thanks for finding this and for opening the PR! I left a comment, please take a look whenever you can and then I'm happy to merge it.

**Comment by benjitrosch** [comment]
Fixed by #405
