### ISSUE TITLE
Menu dropdown doesn't close after click?

### ISSUE THREAD

**Issue by seba5devcmps** [daisyui/react-daisyui#412]
Before updating to Daisy 3^ and React Daisy 4^ when clicking on a button in a Menu Dropdown it closes automatically, now it needs to be closed manually, there's any config to keep it like before? Thank you

**Comment by yoshi6jp** [comment]
The befavior is different when using the `<detail>` tag.

## `<detail>` 
- [daisyUI](https://daisyui.com/components/dropdown/#dropdown-menu-using-details-tag)
- [react-daisyUI](https://react.daisyui.com/?path=/story/actions-dropdown-details--default)

## `<div>`
- [daisyUI](https://daisyui.com/components/dropdown/#method-2-using-label-and-css-focus)
- [react-daisyUI](https://react.daisyui.com/?path=/story/actions-dropdown--default)

**Comment by seba5devcmps** [comment]
Got it, It's perfect, thank you so much
