### ISSUE TITLE
Feat: Debounce option for `Input` component

### ISSUE THREAD

**Issue by exoRift** [daisyui/react-daisyui#441]
Add an optional arg for the input component that [debounces](https://dev.to/manishkc104/debounce-input-in-react-3726)

**Comment by benjitrosch** [comment]
@exoRift I'm afraid this would go against one of the goals of the library which is to add a pretty close-to-native-HTML and un-opinionated React wrapper, and leave any specific logic/implementations up to the developer.

If you want to create your own generic debounce hook for React, this result from a Google search looks similar to just about every codebase I've worked in: https://www.dawsoncodes.com/posts/9/using-usedebounce-hook-with-react
