### ISSUE TITLE
Vite + React + TS

### ISSUE THREAD

**Issue by iqbalbals** [daisyui/react-daisyui#442]
[plugin:vite:css] [postcss] Cannot find module 'daisyui'
Require stack:
- /Users/rw/Documents/Freelance/vite-react-tw/tailwind.config.js

here my tailwind config 
```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "node_modules/daisyui/dist/**/*.js",
    "node_modules/react-daisyui/dist/**/*.js",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
};```

**Comment by benjitrosch** [comment]
@iqbalbals Have you ran `npm install daisyui` in addition to the `react-daisyui` library? Both packages are required.
