### ISSUE TITLE
How do I get a multi range slider? 

### ISSUE THREAD

**Issue by brandonfake69** [daisyui/react-daisyui#445]
I would like to modify the range slider to be able to be a multi range slider. How do I do that? https://daisyui.com/components/range/

e.g. something like this: https://tailwindcomponents.com/component/multi-range-slider

**Comment by benjitrosch** [comment]
That's something you'll have to build yourself involving a bit of Javascript and magic to support multiple sliders on the same track for a range type Input. At the moment the `daisyui` does not support this and I can't imagine it's on the roadmap.

You can accomplish this by overlaying two range input's over one another, and making sure the max cannot be lower than the min, and vice versa.
