### ISSUE TITLE
Checkbox component doesn't support ghost color

### ISSUE THREAD

**Issue by itaiperi** [daisyui/react-daisyui#448]
Hi,
I've noticed that the `Checkbox` component doesn't support the `ghost` color. Is this intended behavior?

https://github.com/daisyui/react-daisyui/blob/a010e43cc73a5dec8d36a77654da20dbf7aff7d8/src/Checkbox/Checkbox.tsx#L46

**Comment by dev0T** [comment]
I believe that might be the case because the implementations are based on the examples from DaisyUI and on those there isn't an example with checkbox with `ghost` color.

**Comment by benjitrosch** [comment]
That's almost right. The reason there's no example is that the original daisyUI checkbox doesn't support the `ghost` color—so neither can we.
