### ISSUE TITLE
Drawer is not working when on the right side of page

### ISSUE THREAD

**Issue by MrWormsy** [daisyui/react-daisyui#451]
In both the storybook environment and my local environment, the Drawer component does not open at the end of the page and it not shown at all.

[Storybook - **Layout/Drawer** - **Right Side Of Page**](https://react.daisyui.com/?path=/story/layout-drawer--right-side-of-page)

The vanilla [DaisyUI](https://daisyui.com/components/drawer/#drawer-that-opens-from-right-side-of-page) one is working like a charm.

**Comment by MrWormsy** [comment]
I found why.

The example from the Storybook (and the DaisyUI website) does not have those two classes: `ms-[-100vw] w-[stretch]` in the side classes of the drawer, that can be found only in the HTML code of the story and not in the "shown" code.

Once added, it works like a charm, I don't feel like opening a PR for this.

In `src/Drawer/Drawer.stories.tsx`
```diff
RightSideOfPage.args = {
- sideClassName: 'h-full absolute',
+ sideClassName: 'h-full absolute ms-[-100vw] w-[stretch]',
  contentClassName: 'flex h-56 items-center justify-center',
  end: true,
}
```

**Comment by MrWormsy** [comment]
I found why.

The example from the Storybook (and the DaisyUI website) does not have those two classes: `ms-[-100vw] w-[stretch]` in the side classes of the drawer, that can be found only in the HTML code of the story and not in the "shown" code.

Once added, it works like a charm, I don't feel like opening a PR for this.

In `src/Drawer/Drawer.stories.tsx`
```diff
RightSideOfPage.args = {
- sideClassName: 'h-full absolute',
+ sideClassName: 'h-full absolute ms-[-100vw] w-[stretch]',
  contentClassName: 'flex h-56 items-center justify-center',
  end: true,
}
```

**Comment by benjitrosch** [comment]
@MrWormsy thanks for finding this, just committed a fix and will redeploy the Storybook soon.
