### ISSUE TITLE
Theme colour variables are in hsl instead of oklch

### ISSUE THREAD

**Issue by ArianK16a** [daisyui/react-daisyui#466]
https://daisyui.com/docs/colors/
The documentation here states that the css variables should be used like this `oklch(var(--p))`, but the css variables generated in `dist/themes.css` are in hsl format, for example `--p` in `:root` is defined like this: `--p: 258.89 94.378% 51.176%;`.
This is in hsl format (test: enter `hsl(258.89, 94.378%, 51.176%)` on https://convertacolor.com/ and https://oklch.com does not accept the input).

This breaks using the variables as shown in the documentation.
Currently, they can be used using `hsl(...)` instead.

Is this an intended deviation?

**Comment by benjitrosch** [comment]
Hi @ArianK16a , this is not an intentional deviation, this library predates `oklch`. I'm not sure when the base DaisyUI library adopted it, but if they have then so should we.

**Comment by ArianK16a** [comment]
Thanks for you reply. It seems like this isn't an issue with react-daisyui, the daisyui project itself in my project was outdated and updating it allows it to work as expected with react-daisyui!
