### ISSUE TITLE
Where does `Option` come from?

### ISSUE THREAD

**Issue by andrew-enquanta** [daisyui/react-daisyui#468]
In the [docs](https://react.daisyui.com/?path=/story/data-input-select--default), it shows the following code snippet:

```
    const [value, setValue] = useState('default');
  return <div className="flex w-full component-preview p-4 items-center justify-center gap-2 font-sans">
      <Select {...args} value={value} onChange={event => setValue(event.target.value)}>
        <Option value={'default'} disabled>
          Pick your favorite Simpson
        </Option>
        <Option value={'Homer'}>Homer</Option>
        <Option value={'Marge'}>Marge</Option>
        <Option value={'Bart'}>Bart</Option>
        <Option value={'Lisa'}>Lisa</Option>
        <Option value={'Maggie'}>Maggie</Option>
      </Select>
    </div>
```

I seem to be unable to import `Option` from the standard location via `import { Option } from "react-daisyui";`

Thanks.

**Comment by benjitrosch** [comment]
Hi @andrew-enquanta, you can access the `Option` component as a sub-component of the `Select`, like so:

```ts
import { Select } from "react-daisyui"

<Select>
  <Select.Option value="A">A</Select.Option>
</Select>
```

It's an oversight of the library's Storybook examples when the sub-components are imported. I'll submit a fix to clear up any confusion.
