### ISSUE TITLE
Did you mean to import react/jsx-runtime.js?

### ISSUE THREAD

**Issue by balibou** [daisyui/react-daisyui#69]
I have installed the package on a nextjs application (with nx).
I succeed to render a button just like in the quickstart of the readme.

But 2 seconds later, I have an error popping:

```bash
Server Error
Error: Cannot find module '/Users/user/Desktop/folder/node_modules/react/jsx-runtime' imported from /Users/user/Desktop/folder/node_modules/react-daisyui/dist/react-daisyui.modern.js
Did you mean to import react/jsx-runtime.js?
```

```json
"daisyui": "^2.11.0",
"react-daisyui": "^1.7.1"
```

**Comment by benjitrosch** [comment]
Hi @balibou ,

As far as I'm aware this is unfortunately a known issue with Next.js at the moment. However, there is a [fix](https://github.com/vercel/next.js/issues/27977#issuecomment-1009413994) that we've been using on our Next.js applications at work.

Install the package [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules). At the top of your next.config.js add the following line:

```js
const withTM = require('next-transpile-modules')(['react-daisyui'])
```

And then wrap your module.exports using withTM like so:

```js
module.exports = withTM({
  //... your content here
  reactStrictMode: true,
})
```

Make sure to include that reactStrictMode line as well.

**Comment by balibou** [comment]
Hi @benjitrosch,

Thanks for the quick and detailed explanation.
I'll be happy to make it work that way then 😃

**Comment by melissamcewen** [comment]
With the fix do we still have to use next-transpile-modules?

**Comment by nelsonlaidev** [comment]
Still not working in `react`
reproduce: https://stackblitz.com/edit/daisyui-react-cra-cojacw
