### ISSUE TITLE
Missing Storybook examples

### ISSUE THREAD

**Issue by benjitrosch** [daisyui/react-daisyui#98]
We want to achieve full coverage of our components in Storybook. This means all features and design options available to users are represented by a separate story.

At the very minimum, we want to show as much as the official [daisyUI](https://daisyui.com) docs show to demonstrate that everything has been ported over for this React wrapper.

Here are the components missing stories from the daisyUI docs:

- [X] Dropdown
- [X] Modal
- [X] KBD
- [X] Stats
- [X] Input
- [X] Rating
- [X] Select
- [X] TextArea
- [X] Drawer
- [X] Hero
- [X] InputGroup
- [X] Mask
- [X] Breadcrumbs
- [X] Menu
- [X] Navbar
- [X] Steps
- [x] Tabs

**Comment by redxzeta** [comment]
I'll work on Hero :)

**Comment by Spelchure** [comment]
Tabs story book merged #191. Issue should be closed

**Comment by benjitrosch** [comment]
@Spelchure Good catch, closing now
